export const ROUTES = {
  home: '',
  login: '/auth/login',
  register: '/auth/register',
  purchasedCourse: '/purchased-course',
  account: '/user/account',
  order: '/user/order',
  detailCourse: '/course',
  lecture: 'lecture',
  problemRepository: 'problem-repository',
  problem: 'problem',
  admin: '/admin',
  adminCourse: '/admin/course',
  adminCreateCourse: '/admin/course/create',
  adminCourseEdit: '/admin/course/:id/edit',
  adminLecture: '/admin/lecture',
} as const;
